# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1731cb970a367f36241df1b4074b38ab334160cc666ce0df27336b6a30729b4f0ba7728224defb8d5c4462492ef6d2741886b005d9bfec9fa0b99cc852ca63e7

test:
  secret_key_base: f847bbbec86142f72d29ceb9267edc0bc66719ac1582a7383f98cd095a14b62a7b4bd56bd8a0e5788726ee8dab34757d42119dd0e2b242cb3bdcd0704ff537fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
